execute pathogen#infect()
syntax enable
syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

:nnoremap <C-x> :NERDTreeToggle<CR>
:nmap ; :

set relativenumber
set laststatus=2
set clipboard=unnamedplus
set statusline+=%F

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

autocmd VimLeave * call system("xsel -ib", getreg('+'))
autocmd vimenter * silent! lcd %:p:h

let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>
