execute pathogen#infect()
syntax enable
syntax on
filetype plugin indent on
set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab

:nnoremap <C-x> :NERDTreeToggle<CR>
:nmap ; :

set relativenumber
set laststatus=2
set clipboard=unnamedplus
set statusline+=%F

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

" White Space             
scriptencoding utf-8
set encoding=utf-8
set listchars=eol:¬,tab:»\ ,trail:.,nbsp:·,extends:→,precedes:←
highlight NonText ctermfg=8 guifg=#c5c8c0
highlight SpecialKey ctermfg=8 guifg=#c5c8c0
set list
setlocal conceallevel=2 concealcursor=inc

autocmd Syntax * syn match LeadingWS /\%(^\s*\)\@<= / containedin=ALLBUT,TrailingWS conceal cchar=.
autocmd Syntax * highlight Conceal ctermbg=NONE ctermfg=238 guifg=#c5c8c0


autocmd VimLeave * call system("xsel -ib", getreg('+'))
autocmd vimenter * silent! lcd %:p:h

let g:tmux_navigator_no_mappings = 1
nnoremap <silent> <c-h> :TmuxNavigateLeft<cr>
nnoremap <silent> <c-j> :TmuxNavigateDown<cr>
nnoremap <silent> <c-k> :TmuxNavigateUp<cr>
nnoremap <silent> <c-l> :TmuxNavigateRight<cr>

nnoremap <silent> <c-p> :CtrlP<cr>
let g:ctrlp_custom_ignore = '\v[\/](node_modules|dist|build)|(\.(swp|ico|git))$'
