execute pathogen#infect()
syntax enable
syntax on
" set background=dark
" colorscheme solarized
" set t_Co=16
" let g:solarized_termcolors=16
filetype plugin indent on
set tabstop=2
set shiftwidth=4
set softtabstop=2

:nnoremap <C-x> :NERDTreeToggle<CR>
:nmap ; :

set relativenumber
set laststatus=2
set clipboard=unnamedplus
set statusline+=%F

noremap <Up> <NOP>
noremap <Down> <NOP>
noremap <Left> <NOP>
noremap <Right> <NOP>

autocmd VimLeave * call system("xsel -ib", getreg('+'))
autocmd vimenter * silent! lcd %:p:h
