#!/bin/sh

# /etc/X11/xinit/xinitrc
#
# global xinitrc file, used by all X sessions started by xinit (startx)

wmname LG3D &
unity-settings-daemon &
google-chrome &

guake --exec='/home/ewnd9/dotfiles/scripts/twitter.tmux' &
nm-applet &
indicator-cpufreq &
prime-indicator &

dropbox start &

record-desktop &
$HOME/.npm-packages/bin/forever $HOME/.npm-packages/bin/xavier-server &

gnome-terminal -e '/home/ewnd9/dotfiles/scripts/tmux/weechat.tmux' &
hain &

(sleep 5 && setxkbmap -layout 'us,ru' -option '' -option 'grp:alt_shift_toggle' -option 'caps:escape' -option 'lv3:ralt_switch' -option 'misc:typo' && xmodmap -e "keycode 135 = Return") &

# invoke global X session script
awesome
