# Set up the prompt

source $HOME/.zsh/prompt/async.zsh
source $HOME/.zsh/prompt/pure.zsh

PURE_GIT_PULL=0
PURE_PROMPT_SYMBOL=λ
# source $HOME/.zsh/git-prompt/zshrc.sh
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

source $HOME/.zsh/zsh-notify/notify.plugin.zsh
zstyle ':notify:*' command-complete-timeout 10

git_super_status() {
  precmd_update_git_vars

  if [ -n "$__CURRENT_GIT_STATUS" ]; then
    STATUS="$ZSH_THEME_GIT_PROMPT_PREFIX$ZSH_THEME_GIT_PROMPT_BRANCH$GIT_BRANCH%{${reset_color}%}"
    STATUS=" $STATUS%{${reset_color}%}$ZSH_THEME_GIT_PROMPT_SUFFIX"
    echo "$STATUS"
  fi
}

# PROMPT='%F{yellow}%Bλ %~%b$(git_super_status)%f %# '

setopt histignorealldups sharehistory
# https://unix.stackexchange.com/questions/310540/how-to-get-rid-of-no-match-found-when-running-rm
setopt +o nomatch

# disable ctrl+s https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
stty -ixon

# 10ms for key sequences
KEYTIMEOUT=1
# REPORTTIME=10

bindkey -e

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

fpath=(~/.zsh/completion $fpath)

fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

# Use modern completion system
autoload -Uz compinit
compinit

# zstyle ':completion:*' menu select=2
# zstyle ":completion:*:descriptions" format "%B%d%b"
# zstyle ":completion:*:commands" rehash 1

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

eval "$(dircolors -b)"

##### ewnd9

synclient TapButton3=2

bindkey "^x" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word

source ~/.zsh/aliases.zsh

export EDITOR=vim
export BROWSER=google-chrome
export LC_TIME=en_US.UTF-8

# https://unix.stackexchange.com/questions/230238/starting-x-applications-from-the-terminal-and-the-warnings-that-follow
export NO_AT_BRIDGE=1 #

export ANDROID_HOME="$HOME/.android-sdk"
export PATH="$HOME/.android-sdk/platform-tools:$PATH"
export PATH="$HOME/.android-sdk/tools/bin:$PATH"
export JAVA_HOME="/usr/lib/jvm/java-8-oracle"

export NODE_PATH=$NODE_PATH:$HOME/.npm-packages/lib/node_modules

export GOPATH="$HOME/gocode"
export PATH="$PATH:$HOME/gocode/bin"

export PATH="$HOME/.cargo/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH" # pip

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH="$HOME/.rbenv/plugins/ruby-build/bin:$PATH"

export PATH="$HOME/soft/android-sdk/tools:$PATH"
export PATH="$HOME/soft/android-sdk/platform-tools:$PATH"
export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$PATH:$HOME/.npm-packages/bin"
export PATH="/usr/local/heroku/bin:$PATH"

[ -f $HOME/Dropbox/dotfiles/aliases.zsh ] && source $HOME/Dropbox/dotfiles/aliases.zsh

TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'
eval $( perl -Mlocal::lib )
