export LANG="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

TIMEFMT=$'\nreal\t%E\nuser\t%U\nsys\t%S'

source $HOME/.zsh/prompt/async.zsh
source $HOME/.zsh/prompt/pure.zsh

if [[ "$OSTYPE" == *darwin* ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
  export CPLUS_INCLUDE_PATH=/opt/homebrew/include
fi

PURE_GIT_PULL=0
PURE_PROMPT_SYMBOL=λ
# source $HOME/.zsh/git-prompt/zshrc.sh
source $HOME/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

source $HOME/.zsh/zsh-notify/notify.plugin.zsh
zstyle ':notify:*' command-complete-timeout 10

git_super_status() {
  precmd_update_git_vars

  if [ -n "$__CURRENT_GIT_STATUS" ]; then
    STATUS="$ZSH_THEME_GIT_PROMPT_PREFIX$ZSH_THEME_GIT_PROMPT_BRANCH$GIT_BRANCH%{${reset_color}%}"
    STATUS=" $STATUS%{${reset_color}%}$ZSH_THEME_GIT_PROMPT_SUFFIX"
    echo "$STATUS"
  fi
}

# PROMPT='%F{yellow}%Bλ %~%b$(git_super_status)%f %# '

setopt histignorealldups sharehistory
# https://unix.stackexchange.com/questions/310540/how-to-get-rid-of-no-match-found-when-running-rm
setopt +o nomatch

# disable ctrl+s https://unix.stackexchange.com/questions/72086/ctrl-s-hang-terminal-emulator
stty -ixon

# 10ms for key sequences
KEYTIMEOUT=1
# REPORTTIME=10

# bindkey -e
bindkey -v

HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history

fpath=(~/.zsh/completion $fpath)

fpath=(~/.zsh/functions $fpath)
autoload -U ~/.zsh/functions/*(:t)

# Use modern completion system
autoload -Uz compinit

# https://stackoverflow.com/questions/890620/unable-to-have-bash-like-c-x-e-in-zsh
autoload -U edit-command-line
zle -N edit-command-line
bindkey -M vicmd v edit-command-line

compinit

# zstyle ':completion:*' menu select=2
# zstyle ":completion:*:descriptions" format "%B%d%b"
# zstyle ":completion:*:commands" rehash 1

zstyle ':completion:*' auto-description 'specify: %d'
zstyle ':completion:*' completer _expand _complete _correct _approximate
zstyle ':completion:*' format 'Completing %d'
zstyle ':completion:*' group-name ''
zstyle ':completion:*' menu select=2
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
zstyle ':completion:*' list-colors ''
zstyle ':completion:*' list-prompt %SAt %p: Hit TAB for more, or the character to insert%s
zstyle ':completion:*' matcher-list '' 'm:{a-z}={A-Z}' 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=* l:|=*'
zstyle ':completion:*' menu select=long
zstyle ':completion:*' select-prompt %SScrolling active: current selection at %p%s
zstyle ':completion:*' use-compctl true
zstyle ':completion:*' verbose true

zstyle ':completion:*:*:kill:*:processes' list-colors '=(#b) #([0-9]#)*=0=01;31'
zstyle ':completion:*:kill:*' command 'ps -u $USER -o pid,%cpu,tty,cputime,cmd'

# eval "$(dircolors -b)"

##### ewnd9

## synclient TapButton3=2

bindkey "^x" forward-word
bindkey "^[[1;5D" backward-word
bindkey "^Y" accept-and-hold
bindkey "^N" insert-last-word

source ~/.zsh/aliases.zsh

export EDITOR=nvim
export BROWSER=google-chrome
export LC_TIME=en_US.UTF-8

# https://unix.stackexchange.com/questions/230238/starting-x-applications-from-the-terminal-and-the-warnings-that-follow
export NO_AT_BRIDGE=1 #

export HOMEBREW_NO_AUTO_UPDATE=1

export ANDROID_SDK_ROOT=$HOME/Library/Android/sdk
export PATH=$PATH:$ANDROID_SDK_ROOT/emulator
export PATH=$PATH:$ANDROID_SDK_ROOT/platform-tools
export PATH=$PATH:$ANDROID_SDK_ROOT/cmdline-tools/latest/bin
# export JAVA_HOME="/usr/lib/jvm/java-11-oracle"
#
[ -f $HOME/Dropbox/dotfiles/aliases.zsh ] && source $HOME/Dropbox/dotfiles/aliases.zsh

# golang
if [[ "$OSTYPE" == *darwin* ]]; then
  export GOPATH=$HOME/golang
  export GOROOT=/opt/homebrew/opt/golang/libexec
else
  export GOROOT="/usr/lib/go"
  export GOPATH="$HOME/golang"
fi
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$GOROOT/bin"

# rust
export PATH="$PATH:$HOME/.cargo/bin"

# node.js
export PATH="$PATH:$HOME/.yarn/bin"
export PATH="$PATH:$HOME/.npm-packages/bin"
export NODE_PATH="$NODE_PATH:$HOME/.npm-packages/lib/node_modules:/usr/local/lib/node_modules"
# export NODE_OPTIONS="--disable-warning=DEP0040 --disable-warning=DEP0170"
function node22 {
  export PATH="/opt/homebrew/opt/node@22/bin:$PATH"
}
function node20 {
  export PATH="/opt/homebrew/opt/node@20/bin:$PATH"
}
# deno
export PATH="$PATH:$HOME/.deno/bin"
# bun
[ -s "$HOME/.bun/_bun" ] && source "$HOME/.bun/_bun"
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

if [[ "$OSTYPE" == *darwin* ]]; then
  export PATH="/opt/homebrew/opt/node@22/bin:$PATH"
  export PATH="/opt/homebrew/opt/libpq/bin:$PATH"
  export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"
else
  export PATH="$PATH:$HOME/.linuxbrew/bin"
fi

# yandex-cloud
[[ -f "$HOME/yandex-cloud/completion.zsh.inc" ]] && source "$HOME/yandex-cloud/completion.zsh.inc"
export PATH="$PATH:$HOME/yandex-cloud/bin"

# sdkman
export SDKMAN_DIR="$HOME/.sdkman"
[[ -s "$HOME/.sdkman/bin/sdkman-init.sh" ]] && source "$HOME/.sdkman/bin/sdkman-init.sh"

# grit - codemods (https://github.com/getgrit/gritql)
export GRIT_INSTALL="$HOME/.grit"
export PATH="$PATH:$GRIT_INSTALL/bin"

# mise - version manager (https://github.com/jdx/mise)
eval "$($HOME/.local/bin/mise activate zsh)"

export PATH="$PATH:$HOME/.iximiuz/labctl/bin"
source <(labctl completion zsh)
export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"


# atuin - shell history (https://github.com/atuinsh/atuin)
# export PATH="$PATH:$HOME/.atuin/bin"
# eval "$(atuin init zsh)"
