run_once("wmname", "LG3D") -- java fix
run_once("unity-settings-daemon")
run_once("xfsettingsd") -- xfce4 settings daemon
run_once("google-chrome")
--run_once("skype")
run_once("telegram")
run_once("guake", "--exec='/home/ewnd9/dotfiles/scripts/twitter.tmux'")
run_once("xfce4-power-manager")
run_once("nm-applet") -- networkingos.execute("/usr/bin/run_once indicator-cpufreq")
run_once("indicator-cpufreq")
run_once("geary")
--run_once("awsetbg", "/home/ewnd9/Pictures/Wallpapers/bluedeath.jpg")
--run_once("xchat")
run_once("setxkbmap", "-layout 'us,ru' -option '' -option 'grp:alt_shift_toggle' -option 'caps:none'")
run_once("dropbox start")
run_once("lastfmsubmitd")
run_once("xmodmap", "~/.Xmodmap") -- caps lock to delete
run_once("synclient", "TapButton3=2") -- middle mouse button on triple touch pad
run_once("xavier")
run_once("/home/ewnd9/soft/copy/x86_64/CopyAgent")
run_once("somebar")
run_once("/home/ewnd9/.npm-packages/bin/workout --test")
run_once("rescuetime")
run_once("gnome-terminal", "-e '/home/ewnd9/dotfiles/scripts/weechat.tmux'")
run_once("albert")
