awful.rules.rules = {
  { rule = { },
    properties = { border_width = beautiful.border_width,
                   border_color = beautiful.border_normal,
                   focus = true,
                   keys = clientkeys,
                   buttons = clientbuttons } },
  { rule = { class = "Chromium" },
    properties = { tag = tags[1][1] } },
  { rule = { class = "Intellij Idea" },
    properties = { tag = tags[1][2] } },
  { rule = { class = "Skype" },
      properties = { tag = tags[1][5] } },
  { rule = { class = "telegram" },
    properties = { tag = tags[1][5] } },
  { rule = { class = "Geary" },
    properties = { tag = tags[1][9] } },
	{ rule = { class = "dictionary-cli" },
	  properties = { floating = false } },
  { rule = { class = "Guake" },
    properties = {opacity = 0.7} },
  { rule = { class = "Terminator" },
    properties = { size_hints_honor = false } },
  { rule = { class = "Gnome-terminal" },
    properties = { size_hints_honor = false } },
  { rule = { class = "feh" }, -- image viewer
    properties = { floating = true } },
  { rule = { class = "Eog" }, -- image viewer
    properties = { floating = true } },
  { rule = { class = "Electron" },
    properties = { floating = true } },
  { rule = { class = "Journal" },
    properties = { floating = true } },
  { rule = { class = "Xavier" },
    properties = { floating = true } }
}
